site_name: 计算机学习指南
site_url: https://cs.meowrain.cn
site_description: >-
  计算机学习指南，这里有从网络上收集的计算机各种方面的知识技能，可供查阅和学习
repo_name: doc-for-cs
repo_url: https://github.com/meowrain/doc-for-sxau
copyright: Copyright &copy; 2023-present <a href="https://github.com/SXAU-Open-Source-Software-Team" target="_blank" rel="noopener noreferrer"></a>
theme:
  language: zh
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
extra:
  homepage: #
markdown_extensions:
  - attr_list # 增加css-html样式，例如按钮，比如图片定义大小，caption
  - pymdownx.tabbed  # C++/python 代码例子切换
  - nl2br # newline-to-break  markdown非严格换行
  - toc:
      permalink: '#' # heading anchor 标题的#样式
      slugify: !!python/name:pymdownx.slugs.uslugify # 默认的解析器遇到中文会有问题，需要改成这个
  - admonition  # 突出显示一些东西，比如 !!!info|bug|tips之类
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes # 支持脚注[^1]
  - meta # 好像是设置页面基本信息的
  - def_list # 支持有序、无序、任务列表
  - pymdownx.arithmatex: # 数学公式latex支持
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic  # 支持markdown高亮==，删除等高级样式
  - pymdownx.emoji:  # 支持图标icons和表情渲染，比如:smile:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
