site_name: 计算机学习指南
site_url: https://cs.meowrain.cn
site_description: >-
  计算机学习指南，这里有从网络上收集的计算机各种方面的知识技能，可供查阅和学习
repo_name: doc-for-cs
repo_url: https://github.com/meowrain/doc-for-sxau
copyright: Copyright &copy; 2023-present <a href="https://github.com/SXAU-Open-Source-Software-Team" target="_blank" rel="noopener noreferrer"></a>
theme:
  language: zh
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
extra:
  homepage: #
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等