site_name: 山西农业大学计算机学习指南
site_url: https://cs.meowrain.cn
site_description: >-
  山西农业大学计算机学习指南，这里有从网络上收集的计算机各种方面的知识技能，可供查阅和学习
repo_name: doc-for-sxau
repo_url: https://github.com/meowrain/doc-for-sxau
copyright: Copyright &copy; 2023-present <a href="https://github.com/SXAU-Open-Source-Software-Team" target="_blank" rel="noopener noreferrer">山西农业大学开源软件爱好者协会</a>
theme:
  language: zh
  name: material
  logo: assets/129314812.jpg
  favicon: assets/129314812.jpg
  palette:
      - primary: pink
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: 切换到黑暗模式
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-3
          name: 切换到白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
extra:
  homepage: #
  constent:
    title: Cookie政策
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等